export type Dua = { id:string; category:string; title:string; arabic:string; transliteration:string; meaning:string; reference:string };
export const DUAS:Dua[]=[
{id:"wake",category:"Morning",title:"When waking up",arabic:"الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ",transliteration:"Alhamdu lillāhilladhī ahyānā ba‘da mā amātanā wa ilayhin-nushūr.",meaning:"All praise is for Allah who gave us life after causing us to die, and to Him is the resurrection.",reference:"Sahih al-Bukhari 6312"},
{id:"sleep",category:"Sleep",title:"Before sleeping",arabic:"بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا",transliteration:"Bismika Allāhumma amūtu wa ahyā.",meaning:"In Your name, O Allah, I die and I live.",reference:"Sahih al-Bukhari 6324"},
{id:"eat",category:"Food",title:"Before eating",arabic:"بِسْمِ اللَّهِ",transliteration:"Bismillāh.",meaning:"In the name of Allah.",reference:"Sunan Abi Dawud 3767"},
{id:"after-eat",category:"Food",title:"After eating",arabic:"الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنِي هَذَا وَرَزَقَنِيهِ مِنْ غَيْرِ حَوْلٍ مِنِّي وَلَا قُوَّةٍ",transliteration:"Alhamdu lillāhilladhī at‘amanī hādhā wa razaqanīhi min ghayri hawlin minnī wa lā quwwah.",meaning:"Praise is to Allah who fed me this and provided it for me without any might or power from me.",reference:"Jami at-Tirmidhi 3458"},
{id:"home-out",category:"Home",title:"Leaving home",arabic:"بِسْمِ اللَّهِ تَوَكَّلْتُ عَلَى اللَّهِ لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ",transliteration:"Bismillāh, tawakkaltu ‘alallāh, lā hawla wa lā quwwata illā billāh.",meaning:"In the name of Allah; I place my trust in Allah. There is no power nor strength except through Allah.",reference:"Sunan Abi Dawud 5095"},
{id:"travel",category:"Travel",title:"Beginning a journey",arabic:"سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ وَإِنَّا إِلَى رَبِّنَا لَمُنْقَلِبُونَ",transliteration:"Subhānalladhī sakhkhara lanā hādhā wa mā kunnā lahu muqrinīn, wa innā ilā rabbinā lamunqalibūn.",meaning:"Glory is to the One who subjected this to us, though we could never have controlled it, and surely to our Lord we will return.",reference:"Quran 43:13–14"},
{id:"anxiety",category:"Wellbeing",title:"For worry and sadness",arabic:"اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ",transliteration:"Allāhumma innī a‘ūdhu bika minal-hammi wal-hazan.",meaning:"O Allah, I seek refuge in You from worry and sadness.",reference:"Sahih al-Bukhari 6369"},
{id:"parents",category:"Family",title:"For parents",arabic:"رَبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا",transliteration:"Rabbirhamhumā kamā rabbayānī saghīrā.",meaning:"My Lord, have mercy upon them as they raised me when I was small.",reference:"Quran 17:24"},
{id:"knowledge",category:"Learning",title:"For beneficial knowledge",arabic:"رَبِّ زِدْنِي عِلْمًا",transliteration:"Rabbi zidnī ‘ilmā.",meaning:"My Lord, increase me in knowledge.",reference:"Quran 20:114"},
{id:"steadfast",category:"Faith",title:"For steadfastness",arabic:"يَا مُقَلِّبَ الْقُلُوبِ ثَبِّتْ قَلْبِي عَلَى دِينِكَ",transliteration:"Yā Muqallibal-qulūb, thabbit qalbī ‘alā dīnik.",meaning:"O Turner of hearts, keep my heart firm upon Your religion.",reference:"Jami at-Tirmidhi 2140"},
];
