import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { Bookmark, Search } from "lucide-react";
import { GuidedPathNav } from "@/components/GuidedPathNav";
import { AudioPlayer } from "@/components/AudioPlayer";
import { DUAS } from "@/lib/duas-data";
import { useBookmarks } from "@/lib/app-state";
export const Route=createFileRoute("/duas/")({component:DuasPage});
function DuasPage(){const [query,setQuery]=useState("");const [category,setCategory]=useState("All");const bookmarks=useBookmarks();const categories=["All",...new Set(DUAS.map(d=>d.category))];const shown=useMemo(()=>DUAS.filter(d=>(category==="All"||d.category===category)&&`${d.title} ${d.meaning} ${d.transliteration}`.toLowerCase().includes(query.toLowerCase())),[query,category]);return <div className="min-h-screen bg-background text-foreground"><GuidedPathNav/><main className="mx-auto max-w-5xl space-y-8 px-5 pb-20"><header className="space-y-3 text-center"><p className="text-xs uppercase tracking-[.2em] text-accent">Remember Allah throughout your day</p><h1 className="font-serif text-5xl italic">Daily Duas</h1><p dir="rtl" className="font-arabic text-3xl text-accent">الأدعية اليومية</p><p className="mx-auto max-w-xl text-muted-foreground">Authentic supplications with Arabic, pronunciation, meaning, references, audio, and bookmarks.</p></header><section className="rounded-3xl border border-border bg-card p-4"><label className="flex items-center gap-3 rounded-2xl bg-background px-4 py-3"><Search className="size-4 text-muted-foreground"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search duas" className="w-full bg-transparent outline-none"/></label><div className="mt-3 flex gap-2 overflow-x-auto pb-1">{categories.map(c=><button key={c} onClick={()=>setCategory(c)} className={`shrink-0 rounded-full px-4 py-2 text-xs ${category===c?"bg-primary text-primary-foreground":"bg-secondary text-muted-foreground"}`}>{c}</button>)}</div></section><div className="grid gap-5 md:grid-cols-2">{shown.map(dua=><article key={dua.id} className="space-y-5 rounded-3xl border border-border bg-card p-6 shadow-sm"><div className="flex justify-between gap-4"><div><p className="text-[10px] uppercase tracking-widest text-accent">{dua.category}</p><h2 className="font-serif text-2xl italic">{dua.title}</h2></div><button onClick={()=>bookmarks.toggle(`dua:${dua.id}`)} aria-label="Bookmark dua" className={`grid size-10 place-items-center rounded-full border border-border ${bookmarks.has(`dua:${dua.id}`)?"bg-accent text-accent-foreground":""}`}><Bookmark className="size-4" fill={bookmarks.has(`dua:${dua.id}`)?"currentColor":"none"}/></button></div><p dir="rtl" className="font-arabic text-3xl leading-loose">{dua.arabic}</p><div className="rounded-2xl bg-secondary/60 p-4"><p className="font-serif text-lg italic">{dua.transliteration}</p></div><p className="text-sm leading-relaxed text-muted-foreground">{dua.meaning}</p><AudioPlayer label="Listen to Arabic" text={dua.arabic}/><p className="border-t border-border pt-3 text-xs text-muted-foreground">{dua.reference}</p></article>)}</div></main></div>}
